name: lifesync
description: "Student wellness app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  fl_chart: ^1.1.1
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.2
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.11.0
  material_symbols_icons: ^4.2892.0
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
    image_path: "assets/logo_with_white_bg.png"
    #image_path_android: "assets/images/icon-710x599-android.png"
    #image_path_ios: "assets/images/icon-1024x1024.png"
    android: true
    ios: true
    adaptive_icon_background: "assets/logo_white_bg.png" # only available for Android 8.0 devices and above
    adaptive_icon_foreground: "assets/logo.png" # only available for Android 8.0 devices and above
    adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
    adaptive_icon_monochrome: "assets/logo_monochrome.png" # only available for Android 13 devices and above
    min_sdk_android: 21 # android min sdk min:16, default 21
    remove_alpha_ios: true
    background_color_ios: "#ffffff"
    web:
        generate: true
        image_path: "assets/logo.png"
        background_color: "#hexcode"
        theme_color: "#hexcode"
    windows:
        generate: true
        image_path: "assets/logo.png"
        icon_size: 48 # min:48, max:256, default: 48
    macos:
        generate: true
        image_path: "assets/logo.png"
